# Generated by Django 5.1.7 on 2025-03-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='medicine_image/'),
        ),
    ]
