# Generated by Django 5.1.7 on 2025-03-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
